language: node_js
node_js:
  - "stable"
  - "7"
sudo: false
notifications:
  email: false
before_install:
  - npm install -g yarn --cache-min 999999999
  - npm install -g bower
  - npm install -g grunt
  - npm install -g grunt-cli
install:
  - yarn
script:
  - npm run package
